###
// get Admin
POST http://localhost:8000/admin/
Content-Type: application/json



###
// Add Admin
POST http://localhost:8000/admin/
Content-Type: application/json

{
    "nama" : "admin2",
    "email" : "admin2@smktelkom-mlg.sch.id",
    "password" : "admin123"
}

###
//Login admin
POST http://localhost:8000/admin/auth
Content-Type: application/json

{
    "email" : "admin@smktelkom-mlg.sch.id",
    "password" : "admin123"
}
